### ISSUE TITLE
 Including fields reason And proof

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [Ali-Hussein-dev/mustaghni-browser-extension#1]
Suggested Solution

by using the _id from the response, we contruct  a URL that leads to brand page on mustaghni.org

```ts
// example for proof and more details. 
const url= `https://mustaghni.org/en/brands/${_id}`
```
@IbrahimMohammed47

**Comment by IbrahimMohammed47** [comment]
@Ali-Hussein-dev 
Sure..  you think the extension should only show (label and logo)?
And for rest of data, the website should be visited?

**Comment by alibey-10** [comment]
> @Ali-Hussein-dev Sure.. you think the extension should only show (label and logo)? And for rest of data, the website should be visited?

Alternatives should be shown directly in the pop-up and details of proof can be shown on Mustaghni.org
